### ISSUE TITLE
Comentar todo o programa

### ISSUE THREAD

**Issue by caio-o** [caio-o/text-processing-c#2]
- [ ] Funções de busca
- [ ] Funções de leitura (fácil)
- [ ] Construtoras e destrutoras (o mais fácil)
- [ ] Structs
- [ ] Menu (fácil)
